### ISSUE TITLE
Consider using font-family:monospace in textarea.

### ISSUE THREAD

**Issue by HyperHCl** [claudehohl/Stikked#237]
Using such setting will allow users to see their text well-aligned in the textarea input box.
The text will look just like what you get after turning on ‘realtime syntax highlighting’ for plain text or when shown in the paste page (Well there is still no line numbers.)

I can see `id="code"` in the `<textarea>` tag, but I can't see anything related to `.code` in my browser.
```CSS
/* This would be enough for me */
.code { font-family: monospace; }
```
* * *
Monospaced code
```
#include<stdio.h>
int main (void) { printf("foo\n"); return 0; }
```
Looks a lot better than
#include&lt;stdio.h&gt;
int main (void) { printf("foo\n"); return 0; }
